In [1]:
import numpy as np

## Tạo mảng 1D

In [ ]:
#Tạo một mảng NumPy 1D chứa 10 số nguyên ngẫu nhiên từ 1 đến 50.
task_1 = np.random.randint(1,51,size=10)
task_1

array([24, 23, 49, 31, 24, 24, 40, 28, 16, 49], dtype=int32)

In [6]:
task_1.shape

(10,)

In [7]:
task_1.dtype

dtype('int32')

## Tạo mảng 2D

In [ ]:
#Tạo một mảng 2D 3x4 với các giá trị từ 1 đến 12
task_2 = np.arange(1,13).reshape(3,4)
task_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#Truy cập phần tử ở vị trí (2, 3) và thay đổi giá trị thành 99.
task_2[2,3] = 99
task_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 99]])

## Tạo mảng đặc biệt

In [ ]:
#Tạo mảng 5x5 toàn số 0
task_3 = np.zeros((5,5))
task_3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
#Tạo mảng 4x4 toàn số 1
task_4 = np.ones((4,4))
task_4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#Tạo một mảng 3x3 với đường chéo chính là 1 và các phần tử khác là 0
task_5 =np.eye(3)
task_5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Thao tác cơ bản

In [25]:
#Tạo mảng 1D chứa 8 số ngẫu nhiên từ 10 đến 100.
task_6 = np.random.randint(10,101,size=8)
task_6

array([95, 41, 29, 34, 93, 77, 38, 31], dtype=int32)

In [ ]:
#In ra các phần tử ở vị trí chẵn
task_6[task_6 % 2 == 0]

array([34, 38], dtype=int32)

## Làm sạch mảng

In [36]:
#Tạo mảng 1D với 10 số ngẫu nhiên, trong đó thêm 2 giá trị np.nan ngẫu nhiên.
task_7 = np.random.randint(1,101,size=10).astype(float)
nan_indices = np.random.choice(len(task_7),size=2,replace=False)
task_7[nan_indices] = np.nan
task_7

array([ 1.,  5., nan, 70., nan, 49., 93., 62., 42., 31.])

In [38]:
#Thay các giá trị np.nan bằng 0.
nan_index = np.isnan(task_7)
task_7[nan_index] = 0
task_7

array([ 1.,  5.,  0., 70.,  0., 49., 93., 62., 42., 31.])