In [1]:
import numpy as np

## Phép toán cơ bản

In [3]:
#Tạo hai mảng 1D với 6 số ngẫu nhiên từ 1 đến 20.
arr_1 = np.random.randint(1,21,size=6)
arr_2 = np.random.randint(1,21,size=6)

In [17]:
#Thực hiện các phép cộng, trừ, nhân, chia giữa hai mảng.
print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[ 7 24 23 25 18 29]
[ -5  16  -7 -11 -14   7]
[  6  80 120 126  32 198]
[0.16666667 5.         0.53333333 0.38888889 0.125      1.63636364]


## Hàm toán học

In [18]:
#Tạo mảng 1D với 10 số ngẫu nhiên từ 1 đến 100.
array = np.random.randint(1,101,size=10)
array

array([27, 15, 64, 89, 97, 80, 70, 73, 99, 34], dtype=int32)

In [19]:
#Tính tổng, trung bình, giá trị lớn nhất, nhỏ nhất và độ lệch chuẩn.
print(array.sum())
print(array.mean())
print(array.max())
print(array.min())
print(array.std()) # độ lệch chuẩn/standard deviation

648
64.8
99
15
28.24110479425336


## Vector hóa

In [22]:
#Tạo mảng 1D chứa 5 số ngẫu nhiên
array_vt = np.arange(5)
array_vt

array([0, 1, 2, 3, 4])

In [23]:
#Tính bình phương của mảng mà không dùng vòng lặp
array_squared = np.square(array_vt)
array_squared

array([ 0,  1,  4,  9, 16])

## Tính toán trên mảng 2D

In [26]:
#Tạo mảng 2D 4x3 với các giá trị từ 1 đến 12
arr_3 = np.arange(1,13).reshape(4,3)
arr_3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
#Tính tổng theo hàng, tổng theo cột, và tổng toàn bộ mảng
print(np.sum(arr_3,axis=0))
print(np.sum(arr_3,axis=1))
print(arr_3.sum())

[22 26 30]
[ 6 15 24 33]
78


## Làm sạch dữ liệu


In [38]:
#Tạo mảng 2D 5x5 với các giá trị ngẫu nhiên từ 1 đến 100, thêm 3 giá trị np.nan ngẫu nhiên.
arr_4 = np.random.randint(1,101,size=(5,5)).astype(float)
flat_indices = np.random.choice(arr_4.size,size=3,replace=False)
rows, cols = np.unravel_index(flat_indices, arr_4.shape)
arr_4[rows, cols] = np.nan
arr_4

array([[92., 78., nan, 31., 73.],
       [nan, 93., 17., nan, 17.],
       [76., 38., 80., 38., 37.],
       [80., 30., 71., 87., 13.],
       [71., 43., 78., 78., 14.]])

In [43]:
#Thay np.nan bằng giá trị trung bình của cột tương ứng.
col_mean = np.nanmean(arr_4,axis=0)
inds = np.where(np.isnan(arr_4))
arr_4[inds] = np.take(col_mean,inds[1])
arr_4

array([[92.  , 78.  , 61.5 , 31.  , 73.  ],
       [79.75, 93.  , 17.  , 58.5 , 17.  ],
       [76.  , 38.  , 80.  , 38.  , 37.  ],
       [80.  , 30.  , 71.  , 87.  , 13.  ],
       [71.  , 43.  , 78.  , 78.  , 14.  ]])