In [2]:
import numpy as np

In [3]:
#Tạo một mảng NumPy 1D với 10 số nguyên ngẫu nhiên từ 1 đến 100.
arr_1 = np.random.randint(1,101,size=10)
arr_1

array([ 30,  18,  93,   9, 100,  46,  98,  33,  20,  76], dtype=int32)

In [15]:
#Tạo một mảng 2D 3x3 với các giá trị từ 1 đến 9.
arr_2 = np.arange(1,10).reshape(3,3)
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#In ra phần tử ở vị trí (1, 2) của mảng 2D.
print(arr_2[1,2])

6


In [6]:
#Thay đổi giá trị của phần tử ở vị trí (1, 1) thành 10.
arr_2[1,1] = 10
arr_2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [7]:
arr_2[2,2] = 8
arr_2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  8]])