In [2]:
import numpy as np

In [7]:
np.random.seed(0)

In [8]:
#Tạo hai mảng 1D với 5 phần tử ngẫu nhiên từ 1 đến 10.
arr1 = np.random.randint(1,11,size=5)
arr2 = np.random.randint(1,11,size=5)

In [10]:
arr1

array([6, 1, 4, 4, 8], dtype=int32)

In [ ]:
arr2

array([10,  4,  6,  3,  5], dtype=int32)

In [13]:
#Thực hiện các phép cộng, trừ, nhân hai mảng này.
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[16  5 10  7 13]
[-4 -3 -2  1  3]
[60  4 24 12 40]


In [18]:
#Tính tổng, trung bình, giá trị lớn nhất và nhỏ nhất của mảng thứ nhất.
print(arr1.sum())
print(arr1.mean())
print(arr1.max())
print(arr1.min())

23
4.6
8
1


In [22]:
#Tạo một mảng 2D 4x4 và tính tổng theo hàng và cột.
np.random.seed(0)
arr3 = np.random.randint(1,11,size=(4,4))
arr3

array([[ 6,  1,  4,  4],
       [ 8, 10,  4,  6],
       [ 3,  5,  8,  7],
       [ 9,  9,  2,  7]], dtype=int32)

In [23]:
row_sum = np.sum(arr3,axis=1)
row_sum

array([15, 28, 23, 27])

In [24]:
col_sum = np.sum(arr3,axis=0)
col_sum

array([26, 25, 18, 24])